// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9I3MLO-htX2n4oAXwgiNB7iEdg0EC1o',
    appId: '1:650580724445:web:b5e041c704a3384cbca934',
    messagingSenderId: '650580724445',
    projectId: 'fineace-app-eae93',
    authDomain: 'fineace-app-eae93.firebaseapp.com',
    storageBucket: 'fineace-app-eae93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqdjmEZy42npg4YLvkrGhHDXyyhUmt40M',
    appId: '1:650580724445:android:1a1ea498924d55c1bca934',
    messagingSenderId: '650580724445',
    projectId: 'fineace-app-eae93',
    storageBucket: 'fineace-app-eae93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGtaQoLoXKTh2CW5FlO_v68pBTBX8jYPE',
    appId: '1:650580724445:ios:8d4a3e786f205ac8bca934',
    messagingSenderId: '650580724445',
    projectId: 'fineace-app-eae93',
    storageBucket: 'fineace-app-eae93.firebasestorage.app',
    iosBundleId: 'com.example.fineace',
  );
}
